In [2]:
import pandas as pd
import numpy as np
movies = pd.read_csv('input/tmdb_5000_movies.csv')
credits = pd.read_csv('input/tmdb_5000_credits.csv')
movies=movies.merge(credits,on='title')
#now we use only some for recommendition
# movie_id,title,release_date,genres,keywords,overview,cast,crew
movies=movies[['movie_id','title','release_date','genres','overview','keywords','cast','crew']]
movies.head(1)

,movie_id,title,release_date,genres,overview,keywords,cast,crew
0,19995,Avatar,2009-12-10,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [3]:
movies.isnull().sum()

movie_id        0
title           0
release_date    1
genres          0
overview        3
keywords        0
cast            0
crew            0
dtype: int64

In [4]:
movies.dropna(inplace=True)
movies.isnull().sum()

movie_id        0
title           0
release_date    0
genres          0
overview        0
keywords        0
cast            0
crew            0
dtype: int64

In [5]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [6]:
movies['genres']=movies['genres'].apply(convert)
movies['keywords']=movies['keywords'].apply(convert)
movies['cast']=movies['cast'].apply(convert)
movies.head(1)

,movie_id,title,release_date,genres,overview,keywords,cast,crew
0,19995,Avatar,2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
import ast
def director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append('name')
            break
    return L

In [8]:
movies['crew']=movies['crew'].apply(director)
movies['overview'][0]
#making overview column split in list
movies['overview']=movies['overview'].apply(lambda x:x.split())
movies.head()

,movie_id,title,release_date,genres,overview,keywords,cast,crew
0,19995,Avatar,2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[name]
1,285,Pirates of the Caribbean: At World's End,2007-05-19,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[name]
2,206647,Spectre,2015-10-26,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[name]
3,49026,The Dark Knight Rises,2012-07-16,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[name]
4,49529,John Carter,2012-03-07,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[name]

In [9]:
#removig spaces in words
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['overview']=movies['overview'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies.head(1)

,movie_id,title,release_date,genres,overview,keywords,cast,crew
0,19995,Avatar,2009-12-10,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[name]

In [10]:
new_file=movies[['movie_id','title','genres','release_date','overview',]]
new_file['overview']=new_file['overview'].apply(lambda x:" ".join(x))
new_file

C:\Users\bonir\AppData\Local\Temp\ipykernel_2844\1300235444.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_file['overview']=new_file['overview'].apply(lambda x:" ".join(x))

,movie_id,title,genres,release_date,overview
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",2009-12-10,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",2007-05-19,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[Action, Adventure, Crime]",2015-10-26,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",2012-07-16,Following the death of District Attorney Harve...
4,49529,John Carter,"[Action, Adventure, ScienceFiction]",2012-03-07,"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]",1992-09-04,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,"[Comedy, Romance]",2011-12-26,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie]",2013-10-13,"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,[],2012-05-03,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,[Documentary],2005-08-05,Ever since the second grade when he first saw ...

In [11]:
new_file['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [12]:
new_file['overview']=new_file['overview'].apply(lambda x:x.lower())

C:\Users\bonir\AppData\Local\Temp\ipykernel_2844\2445808766.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_file['overview']=new_file['overview'].apply(lambda x:x.lower())

In [13]:
new_file.head(1)

,movie_id,title,genres,release_date,overview
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",2009-12-10,"in the 22nd century, a paraplegic marine is di..."

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(new_file['overview']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
cv.get_feature_names()

C:\Users\bonir\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1920',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1979',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1994',
 '1997',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2008',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 '70s',
 '7th',
 'aaron',
 'abandoned',
 'abandons',
 'abducted',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abroad',
 'absence',
 'abuse',
 'abused',
 'abusive',
 'academic',
 'academy',
 'accept',
 'acceptance',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'accomplished',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'ad',
 'ada',
 'adam',
 'adams',
 'adaptation',
 'adapted',
 'add',
 'addict',
 'addicted',
 'addiction',
 'addition',
 'addled',
 'adds',
 'adjust',
 'admiral',
 'admits',
 'adolescent',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adorable',
 'adrenaline',
 'adrift',
 'adult',
 'adulthood',
 'adults',
 'advanced',
 'advantage',
 'adventure',
 'adventures',
 'adventurous',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affections',
 'affluent',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'afterlife',
 'aftermath',
 'afternoon',
 'age',
 'aged',
 'agency',
 'agenda',
 'agent',
 'agents',
 'ages',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'ailing',
 'aim',
 'air',
 'airborne',
 'aircraft',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'alaskan',
 'albert',
 'alcohol',
 'alcoholic',
 'alex',
 'alexander',
 'alexia',
 'alfie',
 'algeria',
 'ali',
 'alice',
 'alien',
 'aliens',
 'alike',
 'alive',
 'allegedly',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpha',
 'alter',
 'altered',
 'altering',
 'alternate',
 'alternative',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitions',
 'ambitious',
 'ambushed',
 'america',
 'american',
 'americans',
 'amid',
 'amidst',
 'amp',
 'amusement',
 'amusing',
 'amy',
 'ana',
 'anakin',
 'analyst',
 'ancient',
 'anderson',
 'andrew',
 'andy',
 'angel',
 'angela',
 'angeles',
 'angels',
 'anger',
 'angry',
 'animal',
 'animals',
 'animated',
 'ann',
 'anna',
 'anne',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymous',
 'answer',
 'answers',
 'anthony',
 'anti',
 'antics',
 'apart',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approached',
 'approaches',
 'approaching',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'arm',
 'armed',
 'armored',
 'arms',
 'army',
 'arnold',
 'arranged',
 'arrangement',
 'arranges',
 'array',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificial',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistance',
 'assistant',
 'assortment',
 'assume',
 'assumes',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'athletes',
 'athletic',
 'atlantic',
 'atomic',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attend',
 'attendant',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austrian',
 'author',
 'authorities',
 'authority',
 'auto',
 'autobiographical',
 'available',
 'avenge',
 'average',
 'avoid',
 'avoiding',
 'await',
 'awaits',
 'awake',
 'awakens',
 'award',
 'awards',
 'away',
 'awesome',
 'awkward',
 'awry',
 'axel',
 'babe',
 'babies',
 'baby',
 'bachelor',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'backstage',
 'backwater',
 'backyard',
 'bad',
 'badly',
 'bag',
 'bail',
 'baker',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'banished',
 'bank',
 'banker',
 'bar',
 'barbara',
 'barely',
 'bargained',
 'barn',
 'barnes',
 'barney',
 'baron',
 'barriers',
 'barry',
 'bars',
 'base',
 'baseball',
 'based',
 'basement',
 'basis',
 'basketball',
 'batman',
 'battalion',
 'battle',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beats',
 'beau',
 'beautiful',
 'beauty',
 'becky',
 'bed',
 'bedroom',
 'bee',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'bella',
 'belong',
 'belongs',
 'beloved',
 'ben',
 'bending',
 'beneath',
 'benefit',
 'benjamin',
 'bennett',
 'bent',
 'berlin',
 'bernie',
 'best',
 'bet',
 'beth',
 'bethany',
 'betrayal',
 'betrayed',
 'bets',
 'better',
 'betty',
 'beverly',
 'biblical',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikers',
 'bilbo',
 'billion',
 'billionaire',
 'billy',
 'biographical',
 'biography',
 'biopic',
 'bird',
 'birdee',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blackmail',
 'blade',
 'blake',
 'blame',
 'blart',
 'blind',
 'bliss',
 'block',
 'blofeld',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'bloom',
 'blossoms',
 'blow',
 'blows',
 'blu',
 'blue',
 'bly',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobby',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bolt',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'boo',
 'book',
 'books',
 'boots',
 'booze',
 'border',
 'borders',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bourne',
 'bout',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'brain',
 'brand',
 'brandon',
 'brave',
 'brazil',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breathing',
 'brent',
 'brewing',
 'brian',
 'bride',
 'bridge',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'brutally',
 'buck',
 'buddies',
 'buddy',
 'budget',
 'build',
 'building',
 'builds',
 'built',
 'bully',
 'bumbling',
 'bunch',
 'bunny',
 'buried',
 'burned',
 'burns',
 'burton',
 'bury',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butch',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buys',
 'buzz',
 'cabin',
 'cable',
 'caesar',
 'caine',
 'cal',
 'calculating',
 'caleb',
 'california',
 'called',
 'calling',
 'calls',
 'calm',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camp',
 'campaign',
 'campbell',
 'camps',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'canine',
 'capable',
 'cape',
 'capital',
 'capone',
 'capt',
 'captain',
 'captive',
 'captors',
 'capture',
 'captured',
 'captures',
 'capturing',
 'car',
 'card',
 'care',
 'career',
 'careers',
 'carefree',
 'cares',
 'caretaker',
 'cargo',
 'caribbean',
 'carl',
 'carmen',
 'carol',
 'carolina',
 'carpenter',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'case',
 'cases',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'catherine',
 'catholic',
 'cats',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'cesar',
 'chad',
 'chagrin',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'challenging',
 'chamber',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charges',
 'charismatic',
 'charles',
 'charlie',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'cheating',
 'checks',
 'chef',
 'chemical',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chipmunks',
 'chloe',
 'chocolate',
 'choice',
 'choices',
 'chon',
 'choose',
 'chooses',
 'chosen',
 'chris',
 'chrissie',
 'christ',
 'christian',
 'christina',
 'christine',
 'christmas',
 'christopher',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cindy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilians',
 'civilization',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climb',
 'climbing',
 'clique',
 'clock',
 'clone',
 'close',
 'closed',
 'closer',
 'closing',
 'closure',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'coastal',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'col',
 'cold',
 'cole',
 'coleridge',
 'colin',
 'collapse',
 'collapses',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collective',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comfort',
 'comfortable',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commanding',
 'commandos',
 'commercial',
 'commissioned',
 'commit',
 'commitment',
 'commits',
 'committed',
 'common',
 'communicate',
 'communication',
 'communist',
 'community',
 'companion',
 'companions',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'compound',
 'compton',
 'compulsive',
 'computer',
 'conan',
 'concerning',
 'concerns',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confederate',
 'confidence',
 'confident',
 'conflict',
 'conflicts',
 'confront',
 'confrontation',
 'confronted',
 'confronts',
 'confused',
 'connect',
 'connected',
 'connecticut',
 'connection',
 'connections',
 'connects',
 'connery',
 'connie',
 'connor',
 'conquer',
 'conquest',
 'conrad',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'considers',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'containing',
 'contains',
 'contemporary',
 'contend',
 'content',
 'contest',
 'continent',
 'continue',
 'continued',
 'continues',
 'continuing',
 'contract',
 'contracts',
 'control',
 'controlled',
 'controlling',
 'controls',
 'controversial',
 'convention',
 ...]

In [16]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [17]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization.'

In [18]:
new_file['overview']=new_file['overview'].apply(stem)

C:\Users\bonir\AppData\Local\Temp\ipykernel_2844\851092864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_file['overview']=new_file['overview'].apply(stem)

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
similarity[0]

array([1., 0., 0., ..., 0., 0., 0.])

In [20]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 0.9999999999999998),
 (151, 0.2773500981126146),
 (3608, 0.2631174057921088),
 (529, 0.173259232729684),
 (2136, 0.16012815380508716),
 (1216, 0.13355611265883557),
 (1616, 0.1307440900921227),
 (1790, 0.1307440900921227),
 (2622, 0.1307440900921227),
 (568, 0.12725695259515554),
 (942, 0.12725695259515554),
 (972, 0.12403473458920845),
 (973, 0.12403473458920845),
 (1277, 0.12267912301642961),
 (2971, 0.12267912301642961),
 (150, 0.12136700910941023),
 (2620, 0.12104550653376049),
 (3340, 0.12104550653376049),
 (1965, 0.1188643277625491),
 (3622, 0.11826247919781652),
 (1534, 0.11766968108291043),
 (2880, 0.11322770341445959),
 (1161, 0.11094003924504584),
 (311, 0.10878565864408425),
 (36, 0.10675210253672476),
 (1344, 0.10675210253672476),
 (1920, 0.10675210253672476),
 (988, 0.10482848367219183),
 (3423, 0.10482848367219183),
 (3497, 0.10482848367219183),
 (74, 0.10300524052492095),
 (199, 0.10300524052492095),
 (281, 0.10300524052492095),
 (847, 0.10212858423763307),
 (312, 0.10127393670836667),
 (3310, 0.10127393670836667),
 (149, 0.09805806756909201),
 (570, 0.09805806756909201),
 (1201, 0.09805806756909201),
 (1321, 0.09805806756909201),
 (2232, 0.09805806756909201),
 (2634, 0.09805806756909201),
 (3505, 0.09805806756909201),
 (507, 0.09656090991705353),
 (1175, 0.09656090991705353),
 (1278, 0.09656090991705353),
 (1191, 0.09513029883089881),
 (2333, 0.09376144618769908),
 (487, 0.09245003270420485),
 (1808, 0.09245003270420485),
 (3072, 0.09245003270420485),
 (3730, 0.09245003270420485),
 (3914, 0.09245003270420485),
 (4756, 0.09245003270420485),
 (3225, 0.09119215051751065),
 (83, 0.0888231183368655),
 (1659, 0.0888231183368655),
 (373, 0.08770580193070293),
 (823, 0.08770580193070293),
 (1444, 0.08770580193070293),
 (1769, 0.08770580193070293),
 (1973, 0.08770580193070293),
 (1019, 0.08459098688756271),
 (27, 0.08362420100070908),
 (31, 0.08362420100070908),
 (495, 0.08362420100070908),
 (1488, 0.08362420100070908),
 (1655, 0.08362420100070908),
 (2376, 0.08362420100070908),
 (2388, 0.08362420100070908),
 (2515, 0.08362420100070908),
 (45, 0.08178608201095307),
 (1639, 0.08178608201095307),
 (68, 0.08006407690254358),
 (134, 0.08006407690254358),
 (275, 0.08006407690254358),
 (2772, 0.08006407690254358),
 (2968, 0.08006407690254358),
 (3462, 0.08006407690254358),
 (1282, 0.07844645405527362),
 (1553, 0.07692307692307693),
 (2057, 0.07692307692307693),
 (2584, 0.07692307692307693),
 (2786, 0.07692307692307693),
 (2882, 0.07692307692307693),
 (3176, 0.07692307692307693),
 (4216, 0.07692307692307693),
 (4332, 0.07692307692307693),
 (4593, 0.07692307692307693),
 (4048, 0.07619393177594594),
 (236, 0.07412493166611013),
 (483, 0.07412493166611013),
 (1036, 0.07412493166611013),
 (1109, 0.07412493166611013),
 (1348, 0.07412493166611013),
 (1408, 0.07412493166611013),
 (2731, 0.07412493166611013),
 (3716, 0.07412493166611013),
 (3976, 0.07412493166611013),
 (4044, 0.07412493166611013),
 (4192, 0.07412493166611013),
 (4351, 0.07412493166611013),
 (4305, 0.0722158144674119),
 (148, 0.07161148740394328),
 (313, 0.07161148740394328),
 (539, 0.07161148740394328),
 (614, 0.07161148740394328),
 (617, 0.07161148740394328),
 (626, 0.07161148740394328),
 (634, 0.07161148740394328),
 (1071, 0.07161148740394328),
 (1288, 0.07161148740394328),
 (1329, 0.07161148740394328),
 (1671, 0.07161148740394328),
 (1741, 0.07161148740394328),
 (1849, 0.07161148740394328),
 (2014, 0.07161148740394328),
 (2199, 0.07161148740394328),
 (2651, 0.07161148740394328),
 (3074, 0.07161148740394328),
 (3253, 0.07161148740394328),
 (3753, 0.07161148740394328),
 (404, 0.06933752452815364),
 (461, 0.06933752452815364),
 (466, 0.06933752452815364),
 (1016, 0.06933752452815364),
 (1274, 0.06933752452815364),
 (2017, 0.06933752452815364),
 (2138, 0.06933752452815364),
 (2955, 0.06933752452815364),
 (3195, 0.06933752452815364),
 (3306, 0.06933752452815364),
 (3355, 0.06933752452815364),
 (3628, 0.06933752452815364),
 (581, 0.06726727939963124),
 (672, 0.06726727939963124),
 (1166, 0.06726727939963124),
 (3502, 0.06726727939963124),
 (3954, 0.06726727939963124),
 (3201, 0.06677805632941779),
 (26, 0.06537204504606135),
 (637, 0.06537204504606135),
 (899, 0.06537204504606135),
 (951, 0.06537204504606135),
 (1045, 0.06537204504606135),
 (3839, 0.06537204504606135),
 (4045, 0.06537204504606135),
 (4631, 0.06537204504606135),
 (1304, 0.06362847629757777),
 (1469, 0.06362847629757777),
 (1473, 0.06362847629757777),
 (2535, 0.06362847629757777),
 (2589, 0.06362847629757777),
 (2817, 0.06362847629757777),
 (2868, 0.06362847629757777),
 (3301, 0.06362847629757777),
 (3316, 0.06362847629757777),
 (3663, 0.06362847629757777),
 (1141, 0.06201736729460423),
 (1275, 0.06201736729460423),
 (1383, 0.06201736729460423),
 (2235, 0.06201736729460423),
 (2556, 0.06201736729460423),
 (2726, 0.06201736729460423),
 (3165, 0.06201736729460423),
 (3647, 0.06201736729460423),
 (3999, 0.06201736729460423),
 (4651, 0.06201736729460423),
 (87, 0.060522753266880246),
 (174, 0.060522753266880246),
 (854, 0.060522753266880246),
 (1015, 0.060522753266880246),
 (1070, 0.060522753266880246),
 (1301, 0.060522753266880246),
 (1420, 0.060522753266880246),
 (1759, 0.060522753266880246),
 (1840, 0.060522753266880246),
 (2022, 0.060522753266880246),
 (2148, 0.060522753266880246),
 (2224, 0.060522753266880246),
 (2689, 0.060522753266880246),
 (2824, 0.060522753266880246),
 (365, 0.05913123959890826),
 (1178, 0.05913123959890826),
 (2072, 0.05913123959890826),
 (2204, 0.05913123959890826),
 (3109, 0.05913123959890826),
 (270, 0.05783149319662403),
 (787, 0.05783149319662403),
 (871, 0.05783149319662403),
 (1037, 0.05783149319662403),
 (1249, 0.05783149319662403),
 (2652, 0.05783149319662403),
 (2669, 0.05783149319662403),
 (3008, 0.05783149319662403),
 (3937, 0.05783149319662403),
 (4798, 0.05783149319662403),
 (91, 0.056613851707229795),
 (646, 0.056613851707229795),
 (794, 0.056613851707229795),
 (875, 0.056613851707229795),
 (894, 0.056613851707229795),
 (1204, 0.056613851707229795),
 (1440, 0.056613851707229795),
 (3022, 0.056613851707229795),
 (3329, 0.056613851707229795),
 (3538, 0.056613851707229795),
 (4112, 0.056613851707229795),
 (4292, 0.056613851707229795),
 (3368, 0.05603318146805258),
 (454, 0.05547001962252292),
 (473, 0.05547001962252292),
 (582, 0.05547001962252292),
 (883, 0.05547001962252292),
 (1401, 0.05547001962252292),
 (1612, 0.05547001962252292),
 (1788, 0.05547001962252292),
 (2632, 0.05547001962252292),
 (2813, 0.05547001962252292),
 (3091, 0.05547001962252292),
 (307, 0.05465623439441968),
 (139, 0.054392829322042126),
 (1535, 0.054392829322042126),
 (1747, 0.054392829322042126),
 (2372, 0.054392829322042126),
 (2502, 0.054392829322042126),
 (3443, 0.054392829322042126),
 (3673, 0.054392829322042126),
 (4125, 0.054392829322042126),
 (4639, 0.054392829322042126),
 (3810, 0.05387724584403653),
 (7, 0.05337605126836238),
 (369, 0.05337605126836238),
 (372, 0.05337605126836238),
 (430, 0.05337605126836238),
 (513, 0.05337605126836238),
 (635, 0.05337605126836238),
 (775, 0.05337605126836238),
 (901, 0.05337605126836238),
 (1519, 0.05337605126836238),
 (1945, 0.05337605126836238),
 (2409, 0.05337605126836238),
 (2414, 0.05337605126836238),
 (2605, 0.05337605126836238),
 (2879, 0.05337605126836238),
 (4080, 0.05337605126836238),
 (43, 0.052414241836095915),
 (557, 0.052414241836095915),
 (1121, 0.052414241836095915),
 (1455, 0.052414241836095915),
 (1531, 0.052414241836095915),
 (1600, 0.052414241836095915),
 (1823, 0.052414241836095915),
 (1963, 0.052414241836095915),
 (2030, 0.052414241836095915),
 (3108, 0.052414241836095915),
 (3574, 0.052414241836095915),
 (4327, 0.052414241836095915),
 (5, 0.051502620262460476),
 (432, 0.051502620262460476),
 (535, 0.051502620262460476),
 (1023, 0.051502620262460476),
 (1281, 0.051502620262460476),
 (1802, 0.051502620262460476),
 (2430, 0.051502620262460476),
 (2709, 0.051502620262460476),
 (2864, 0.051502620262460476),
 (3977, 0.051502620262460476),
 (4656, 0.051502620262460476),
 (2663, 0.05106429211881654),
 (11, 0.05063696835418333),
 (131, 0.05063696835418333),
 (213, 0.05063696835418333),
 (632, 0.05063696835418333),
 (692, 0.05063696835418333),
 (835, 0.05063696835418333),
 (1537, 0.05063696835418333),
 (1538, 0.05063696835418333),
 (2794, 0.05063696835418333),
 (3102, 0.05063696835418333),
 (3701, 0.05063696835418333),
 (549, 0.049813548138671795),
 (1220, 0.049813548138671795),
 (2364, 0.049813548138671795),
 (2547, 0.049813548138671795),
 (3199, 0.049813548138671795),
 (3620, 0.049813548138671795),
 (4484, 0.049813548138671795),
 (184, 0.049029033784546004),
 (588, 0.049029033784546004),
 (758, 0.049029033784546004),
 (1512, 0.049029033784546004),
 (2642, 0.049029033784546004),
 (2692, 0.049029033784546004),
 (3100, 0.049029033784546004),
 (420, 0.048280454958526765),
 (502, 0.048280454958526765),
 (804, 0.048280454958526765),
 (1056, 0.048280454958526765),
 (1202, 0.048280454958526765),
 (1305, 0.048280454958526765),
 (1561, 0.048280454958526765),
 (1733, 0.048280454958526765),
 (2994, 0.048280454958526765),
 (3729, 0.048280454958526765),
 (3795, 0.048280454958526765),
 (4265, 0.048280454958526765),
 (782, 0.047565149415449405),
 (3390, 0.047565149415449405),
 (3735, 0.047565149415449405),
 (4268, 0.047565149415449405),
 (4380, 0.047565149415449405),
 (140, 0.04688072309384954),
 (228, 0.04688072309384954),
 (946, 0.04688072309384954),
 (2264, 0.04688072309384954),
 (2433, 0.04688072309384954),
 (2740, 0.04688072309384954),
 (2940, 0.04688072309384954),
 (3162, 0.04688072309384954),
 (3664, 0.04688072309384954),
 (4317, 0.04688072309384954),
 (1650, 0.046225016352102424),
 (2226, 0.046225016352102424),
 (2924, 0.046225016352102424),
 (4619, 0.046225016352102424),
 (456, 0.04559607525875532),
 (595, 0.04559607525875532),
 (1479, 0.04559607525875532),
 (170, 0.04499212706658476),
 (412, 0.04499212706658476),
 (475, 0.04499212706658476),
 (1357, 0.04499212706658476),
 (1418, 0.04499212706658476),
 (2087, 0.04499212706658476),
 (2802, 0.04499212706658476),
 (3630, 0.04499212706658476),
 (596, 0.04441155916843275),
 (790, 0.04441155916843275),
 (838, 0.04441155916843275),
 (2320, 0.04441155916843275),
 (1846, 0.043852900965351466),
 (4632, 0.043852900965351466),
 (1371, 0.043314808182421),
 (2650, 0.043314808182421),
 (3782, 0.043314808182421),
 (3950, 0.043314808182421),
 (4013, 0.043314808182421),
 (29, 0.042796049251091296),
 (107, 0.042796049251091296),
 (1678, 0.042796049251091296),
 (3560, 0.042796049251091296),
 (4181, 0.042796049251091296),
 (1322, 0.042295493443781355),
 (2200, 0.042295493443781355),
 (2256, 0.042295493443781355),
 (2488, 0.042295493443781355),
 (2549, 0.042295493443781355),
 (3298, 0.042295493443781355),
 (4063, 0.042295493443781355),
 (277, 0.04181210050035454),
 (343, 0.04181210050035454),
 (2153, 0.04181210050035454),
 (2203, 0.04181210050035454),
 (467, 0.041344911529736156),
 (1497, 0.041344911529736156),
 (1684, 0.041344911529736156),
 (4529, 0.041344911529736156),
 (406, 0.040893041005476534),
 (2729, 0.040893041005476534),
 (47, 0.04045566970313674),
 (2054, 0.04045566970313674),
 (3400, 0.04045566970313674),
 (239, 0.04003203845127179),
 (1926, 0.04003203845127179),
 (1992, 0.04003203845127179),
 (2005, 0.04003203845127179),
 (4545, 0.04003203845127179),
 (3, 0.03962144258751637),
 (153, 0.03962144258751637),
 (301, 0.03962144258751637),
 (1002, 0.03962144258751637),
 (2367, 0.03962144258751637),
 (2881, 0.03962144258751637),
 (1007, 0.03922322702763681),
 (1743, 0.03922322702763681),
 (4553, 0.03922322702763681),
 (102, 0.03883678186903087),
 (222, 0.03883678186903087),
 (4051, 0.03883678186903087),
 (230, 0.038461538461538464),
 (1785, 0.038461538461538464),
 (4655, 0.038461538461538464),
 (127, 0.03809696588797297),
 (1828, 0.03809696588797297),
 (1898, 0.03774256780481986),
 (4797, 0.03774256780481986),
 (1120, 0.03673591791853226),
 (206, 0.03641785203646149),
 (785, 0.03641785203646149),
 (1477, 0.03641785203646149),
 (3431, 0.03641785203646149),
 (1918, 0.03610790723370595),
 (342, 0.03551104121142175),
 (2115, 0.03522349768381735),
 (3520, 0.03522349768381735),
 (2150, 0.03466876226407682),
 (3554, 0.034401045807689073),
 (488, 0.03363363969981562),
 (4330, 0.03363363969981562),
 (2049, 0.032461373658059775),
 (4277, 0.032461373658059775),
 (599, 0.03140371465106638),
 (3509, 0.03140371465106638),
 (2166, 0.030628194591584442),
 (4681, 0.030082841879809342),
 (137, 0.02956561979945413),
 (89, 0.026444294267397257),
 (3951, 0.023524528286477348),
 (1, 0.0),
 (2, 0.0),
 (4, 0.0),
 (6, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (12, 0.0),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.0),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (28, 0.0),
 (30, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (44, 0.0),
 (46, 0.0),
 (48, 0.0),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.0),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (78, 0.0),
 (79, 0.0),
 (80, 0.0),
 (81, 0.0),
 (82, 0.0),
 (84, 0.0),
 (85, 0.0),
 (86, 0.0),
 (88, 0.0),
 (90, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (100, 0.0),
 (101, 0.0),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (108, 0.0),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (112, 0.0),
 (113, 0.0),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.0),
 (118, 0.0),
 (119, 0.0),
 (120, 0.0),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (132, 0.0),
 (133, 0.0),
 (135, 0.0),
 (136, 0.0),
 (138, 0.0),
 (141, 0.0),
 (142, 0.0),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (152, 0.0),
 (154, 0.0),
 (155, 0.0),
 (156, 0.0),
 (157, 0.0),
 (158, 0.0),
 (159, 0.0),
 (160, 0.0),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.0),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (185, 0.0),
 (186, 0.0),
 (187, 0.0),
 (188, 0.0),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.0),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.0),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.0),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (223, 0.0),
 (224, 0.0),
 (225, 0.0),
 (226, 0.0),
 (227, 0.0),
 (229, 0.0),
 (231, 0.0),
 (232, 0.0),
 (233, 0.0),
 (234, 0.0),
 (235, 0.0),
 (237, 0.0),
 (238, 0.0),
 (240, 0.0),
 (241, 0.0),
 (242, 0.0),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (251, 0.0),
 (252, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (256, 0.0),
 (257, 0.0),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (264, 0.0),
 (265, 0.0),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (276, 0.0),
 (278, 0.0),
 (279, 0.0),
 (280, 0.0),
 (282, 0.0),
 (283, 0.0),
 (284, 0.0),
 (285, 0.0),
 (286, 0.0),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (295, 0.0),
 (296, 0.0),
 (297, 0.0),
 (298, 0.0),
 (299, 0.0),
 (300, 0.0),
 (302, 0.0),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (306, 0.0),
 (308, 0.0),
 (309, 0.0),
 (310, 0.0),
 (314, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.0),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.0),
 (350, 0.0),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.0),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (361, 0.0),
 (362, 0.0),
 (363, 0.0),
 (364, 0.0),
 (366, 0.0),
 (367, 0.0),
 (368, 0.0),
 (370, 0.0),
 (371, 0.0),
 (374, 0.0),
 (375, 0.0),
 (376, 0.0),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.0),
 (387, 0.0),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.0),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (402, 0.0),
 (403, 0.0),
 (405, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.0),
 (411, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (416, 0.0),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.0),
 (431, 0.0),
 (433, 0.0),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (455, 0.0),
 (457, 0.0),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (468, 0.0),
 (469, 0.0),
 (470, 0.0),
 (471, 0.0),
 (472, 0.0),
 (474, 0.0),
 (476, 0.0),
 (477, 0.0),
 (478, 0.0),
 (479, 0.0),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (489, 0.0),
 (490, 0.0),
 (491, 0.0),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.0),
 (501, 0.0),
 (503, 0.0),
 (504, 0.0),
 (505, 0.0),
 (506, 0.0),
 (508, 0.0),
 (509, 0.0),
 (510, 0.0),
 (511, 0.0),
 (512, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (530, 0.0),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (536, 0.0),
 (537, 0.0),
 (538, 0.0),
 (540, 0.0),
 (541, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (548, 0.0),
 (550, 0.0),
 (551, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.0),
 (556, 0.0),
 (558, 0.0),
 (559, 0.0),
 (560, 0.0),
 (561, 0.0),
 (562, 0.0),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0),
 (566, 0.0),
 (567, 0.0),
 (569, 0.0),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.0),
 (583, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.0),
 (589, 0.0),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (597, 0.0),
 (598, 0.0),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0),
 (608, 0.0),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (615, 0.0),
 (616, 0.0),
 (618, 0.0),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (627, 0.0),
 (628, 0.0),
 (629, 0.0),
 (630, 0.0),
 (631, 0.0),
 (633, 0.0),
 (636, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (655, 0.0),
 (656, 0.0),
 (657, 0.0),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.0),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 ...]

In [21]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:10]

[(151, 0.2773500981126146),
 (3608, 0.2631174057921088),
 (529, 0.173259232729684),
 (2136, 0.16012815380508716),
 (1216, 0.13355611265883557),
 (1616, 0.1307440900921227),
 (1790, 0.1307440900921227),
 (2622, 0.1307440900921227),
 (568, 0.12725695259515554)]

In [22]:
def recommend(movie):
    movie_index=new_file[new_file['title']==movie].index[0]
    distance=similarity[movie_index]
    movies_list=sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:10]
    for i in movies_list:
        print(new_file.iloc[i[0]].title)
    return

In [23]:
recommend('Batman Begins')

Beowulf
Apollo 18
Tears of the Sun
The American
Aliens vs Predator: Requiem
Hanna
Ever After: A Cinderella Story
In Bruges
xXx

In [24]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [27]:
new_file[new_file['title']=='The Lego Movie'].index[0]

744

In [33]:
def recommend(movie):
    index = new_file[new_file['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_file.iloc[i[0]].title)

In [34]:
recommend('Gandhi')

Gandhi, My Father
A Passage to India
Guiana 1838
Barry Lyndon
Ramanujan

In [35]:
pip install pickle

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

In [36]:
import pickle
pickle.dump(new_file,open('movies_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))